import type { Metadata } from "next";
import "@/styles/globals.scss";
import Header from "@/app/components/Non-Reusable/Header/Header";
import Footer from "@/app/components/Non-Reusable/Footer/Footer";
import SmoothScroll from "@/app/components/Reusable/SmoothScroll/SmoothScroll";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <SmoothScroll>{children}</SmoothScroll>
        <Footer />
      </body>
    </html>
  );
}
